### PR TITLE
Build infrastructure.

### PR DESCRIPTION
**Pull request by matkoch**
This is for @akarpov89. Couldn't find an actual fork 🐱

### CODE REVIEW

**Comment by hmemcpy** [comment]
Oh wow, thanks! But I no longer maintain these. Hell, I don't even have a VS/Rider installed :D
Would you like to take ownership of this repo?

**Comment by matkoch** [comment]
I'm very disappointed 😆 

Doesn't @akarpov89 already have commit privileges? It looks like 😃 But I can also take ownership if everyone agrees.

**Comment by hmemcpy** [comment]
> I'm very disappointed 😆 

It's not much use to me being a full time scala dev 😂 

Anyway, I could give you commit privileges, if you like :)

**Comment by matkoch** [comment]
I know, I know 😄  I'm publishing most of the other plugins anyways. So that makes sense :)

Will wait for Andrey's comments though.

**Comment by hmemcpy** [comment]
Already did :)
Thanks for taking care of this!

**Comment by matkoch** [comment]
@akarpov89 it is just a warning and should disappear as soon as I manage to solve it :)

**Pull request merged**
